### ISSUE TITLE
呼叫 add_condition   出現 TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by yaoshihyu2023** [SsallyLin/touchprice#12]
```
    touch = tp.TouchOrderExecutor(api)
    touch_cmd = tp.TouchCmd(code="2890", close=tp.Price(price=18.0, trend="Up"))
    order_cmd = tp.OrderCmd(
        code="2890",
        order=sj.Order(
            action="Buy",
            price=18,
            quantity=1,
            order_type="ROD",
            price_type="LMT",
        ),
    )
    condition = tp.TouchOrderCond(touch_cmd=touch_cmd, order_cmd=order_cmd)
    touch.add_condition(condition)
    touch.show_condition(code="2890")
```

  File "/home/yao/miniconda3/lib/python3.10/site-packages/touchprice/touch_price.py", line 71, in <dictcomp>
    key: dict(value) for key, value in condition.touch_cmd if not key == "code"
TypeError: 'NoneType' object is not iterable

我打印 touch_price.py  condition.touch_cmd 出現下面內容 
 code='2890' close=Price(price=18.0, trend=<Trend.Up: 'Up'>, price_type=<PriceType.LimitPrice: 'LimitPrice'>) buy_price=None sell_price=None high=None low=None volume=None total_volume=None ask_volume=None bid_volume=None

謝謝

**Comment by SsallyLin** [comment]
這邊請你先把pydantic的版本降為1.0，之後會再針對此版本問題修正

**Comment by SsallyLin** [comment]
你本身也有使用到pydantic?感覺是pydantic舊版本不支援某些你使用到的東西

**Comment by yaoshihyu2023** [comment]
```
import touchprice as tp
import shioaji as sj
import json
import os

# https://github.com/SsallyLin/touchprice
# https://sinotrade.github.io/zh_TW/tutor/advanced/touchorder/

def get_account(api, broker_id):
    accounts = api.list_accounts()
    for account in accounts:
        if account.broker_id == broker_id:
            return account


api = sj.Shioaji()
with open(os.environ["HOME"] + "/.mybin/shioaji_token.txt", "r") as f:
    kw_login = json.loads(f.read())
    api.login(**kw_login, contracts_timeout=300000)
    for acc in api.list_accounts():
        print(acc)
    api.set_default_account(get_account(api, "9A9E"))
    account_path = os.environ["HOME"] + "/.mybin/shihyu/"
    print(
        "CA is",
        api.activate_ca(
            f"{account_path}SinoPac.pfx", ca_passwd="xxxxxxx", person_id="xxxxxxxxxx"
        ),
    )
    touch = tp.TouchOrderExecutor(api)
    touch_cmd = tp.TouchCmd(code="2890", close=tp.Price(price=18.0, trend="Up"))
    order_cmd = tp.OrderCmd(
        code="2890",
        order=sj.Order(
            action="Buy",
            price=18,
            quantity=1,
            order_type="ROD",
            price_type="LMT",
        ),
    )
    condition = tp.TouchOrderCond(touch_cmd=touch_cmd, order_cmd=order_cmd)
    touch.add_condition(condition)
    touch.show_condition(code="2890")
```

```
Traceback (most recent call last):
  File "/home/shihyu/github/Jlab/shioaji/test_touchprice.py", line 1, in <module>
    import touchprice as tp
  File "/home/shihyu/miniconda3/lib/python3.10/site-packages/touchprice/__init__.py", line 1, in <module>
    from .touch_price import (
  File "/home/shihyu/miniconda3/lib/python3.10/site-packages/touchprice/touch_price.py", line 1, in <module>
    import shioaji as sj
  File "/home/shihyu/miniconda3/lib/python3.10/site-packages/shioaji/__init__.py", line 29, in <module>
    from shioaji.shioaji import Shioaji
  File "/home/shihyu/miniconda3/lib/python3.10/site-packages/shioaji/shioaji.py", line 7, in <module>
    from shioaji.backend.solace.utils import (
  File "/home/shihyu/miniconda3/lib/python3.10/site-packages/shioaji/backend/solace/__init__.py", line 1, in <module>
    from shioaji.backend.solace.api import SolaceAPI
  File "shioaji/backend/solace/api.pyx", line 57, in init shioaji.backend.solace.api
  File "/home/shihyu/miniconda3/lib/python3.10/site-packages/shioaji/order.py", line 149, in <module>
    class OrderDealRecords(BaseModel):
  File "/home/shihyu/miniconda3/lib/python3.10/site-packages/pydantic/main.py", line 192, in __new__
    fields[ann_name] = ModelField.infer(
  File "/home/shihyu/miniconda3/lib/python3.10/site-packages/pydantic/fields.py", line 259, in infer
    return cls(
  File "/home/shihyu/miniconda3/lib/python3.10/site-packages/pydantic/fields.py", line 236, in __init__
    self.prepare()
  File "/home/shihyu/miniconda3/lib/python3.10/site-packages/pydantic/fields.py", line 301, in prepare
    self._type_analysis()
  File "/home/shihyu/miniconda3/lib/python3.10/site-packages/pydantic/fields.py", line 376, in _type_analysis
    self.type_.__args__[0], 'key_' + self.name, for_keys=True  # type: ignore
  File "/home/shihyu/miniconda3/lib/python3.10/typing.py", line 984, in __getattr__
    raise AttributeError(attr)
AttributeError: __args__. Did you mean: '__ror__'?

```

我只有使用到 import shioaji as sj 看callstack 好像是 shioaji 也會用到？  謝謝

**Comment by SsallyLin** [comment]
應該是python 3.10版本的問題，目前如果想要快速地解決這個問題應該是用其它的python 版本
pydantic的版本問題會在修復一版

**Comment by yaoshihyu2023** [comment]
```
Traceback (most recent call last):
  File "/home/shihyu/github/Jlab/shioaji/test_touchprice.py", line 1, in <module>
    import touchprice as tp
  File "/home/shihyu/miniconda3/envs/py3-9/lib/python3.9/site-packages/touchprice/__init__.py", line 1, in <module>
    from .touch_price import (
  File "/home/shihyu/miniconda3/envs/py3-9/lib/python3.9/site-packages/touchprice/touch_price.py", line 1, in <module>
    import shioaji as sj
  File "/home/shihyu/miniconda3/envs/py3-9/lib/python3.9/site-packages/shioaji/__init__.py", line 29, in <module>
    from shioaji.shioaji import Shioaji
  File "/home/shihyu/miniconda3/envs/py3-9/lib/python3.9/site-packages/shioaji/shioaji.py", line 7, in <module>
    from shioaji.backend.solace.utils import (
  File "/home/shihyu/miniconda3/envs/py3-9/lib/python3.9/site-packages/shioaji/backend/solace/__init__.py", line 1, in <module>
    from shioaji.backend.solace.api import SolaceAPI
  File "shioaji/backend/solace/api.pyx", line 57, in init shioaji.backend.solace.api
  File "/home/shihyu/miniconda3/envs/py3-9/lib/python3.9/site-packages/shioaji/order.py", line 149, in <module>
    class OrderDealRecords(BaseModel):
  File "/home/shihyu/miniconda3/envs/py3-9/lib/python3.9/site-packages/pydantic/main.py", line 192, in __new__
    fields[ann_name] = ModelField.infer(
  File "/home/shihyu/miniconda3/envs/py3-9/lib/python3.9/site-packages/pydantic/fields.py", line 259, in infer
    return cls(
  File "/home/shihyu/miniconda3/envs/py3-9/lib/python3.9/site-packages/pydantic/fields.py", line 236, in __init__
    self.prepare()
  File "/home/shihyu/miniconda3/envs/py3-9/lib/python3.9/site-packages/pydantic/fields.py", line 301, in prepare
    self._type_analysis()
  File "/home/shihyu/miniconda3/envs/py3-9/lib/python3.9/site-packages/pydantic/fields.py", line 376, in _type_analysis
    self.type_.__args__[0], 'key_' + self.name, for_keys=True  # type: ignore
  File "/home/shihyu/miniconda3/envs/py3-9/lib/python3.9/typing.py", line 711, in __getattr__
    raise AttributeError(attr)
AttributeError: __args__

```
python3.9 + pydantic 1.0  也是一樣有類似錯誤

謝謝

**Comment by SsallyLin** [comment]
我這邊是使用python3.7是正常的

**Comment by yaoshihyu2023** [comment]
```
Traceback (most recent call last):
  File "test_touchprice.py", line 44, in <module>
    touch.add_condition(condition)
  File "/home/shihyu/miniconda3/envs/py37/lib/python3.7/site-packages/touchprice/touch_price.py", line 88, in add_condition
    store_condition = self.adjust_condition(condition, touch_contract)
  File "/home/shihyu/miniconda3/envs/py37/lib/python3.7/site-packages/touchprice/touch_price.py", line 70, in adjust_condition
    key: dict(value) for key, value in condition.touch_cmd if not key == "code"
  File "/home/shihyu/miniconda3/envs/py37/lib/python3.7/site-packages/touchprice/touch_price.py", line 70, in <dictcomp>
    key: dict(value) for key, value in condition.touch_cmd if not key == "code"
TypeError: 'NoneType' object is not iterable
```

我改成 3.7 還是會出現～ 


tconds_dict = {
            key: dict(value) for key, value in condition.touch_cmd if not key == "code"
        }

code='2890' close=Price(price=18.0, trend=<Trend.Up: 'Up'>, price_type=<PriceType.LimitPrice: 'LimitPrice'>) buy_price=None sell_price=None high=None low=None volume=None total_volume=None ask_volume=None bid_volume=None

上面是 condition.touch_cmd 打印出來內容, value 是 None 時候 ,  當 key: dict(value)  就會出現 TypeError: 'NoneType' object is not iterable

**Comment by SsallyLin** [comment]
你的pydantic版本是1.0嗎?

**Comment by yaoshihyu2023** [comment]
```
conda install -n py37 python=3.7
pip install touchprice
pip install pydantic==1.0
```

Response Code: 200 | Event Code: 16 | Info: TIC/v1/STK/*/TSE/2890 | Event: Subscribe or Unsubscribe ok
程式記憶體區段錯誤 (核心已傾印)


我裝了 pydantic  1.0 會變成memory crash  我是用 miniconda 環境～ 我測試兩台電腦都是裝完 python3.7  +  pydantic 1.0 會這樣

謝謝

**Comment by yaoshihyu2023** [comment]
git clone https://github.com/SsallyLin/touchprice 下載可以直接call touchprice 可以

但是 pip install touchprice 版本還沒更新

謝謝
